language: node_js
node_js:
  - "7"

sudo: false 
dist: trusty 

env:
    global:
        secure: "qAuFIDNQITDSoQdmyEtbATXDZ0kbC8AzjLCdBmTlHEwXU6VFKoOtci5amWpQbTsFTS9h2/WG1Qt3PIejhbTHhwE2ItM31VzQg0NtbcQdN3Hcmw22mbjEHTRaUgJM18gdGTwThSRfHK4nq9RPeoQC5qqjvCqDv8bZ4RAADQMy7LyaXPKMUR52iB1n7g0DZx55LVbeuB0/JFcXDHh/k6BirrqMrMsIopfDjIsotHPveJ+8wvnkzTEN1n6ZgCCSRQzeYAQ1GhEtByXbfGoNYbrdKbRKqvDvE9Ul3UX3faRy2QR6rgPU753XyKoP5PXrg2B9HnYN9681g1nQTjTFW7AReV1Rzi3hXrg0QRVTxxUMoFncjULxiIo1OrKb/S13s4UFupo7bVJ5xi62n4pOLr+t9DYBqDRcTvtLav7LOf/7nXpLoL1TR129Zu3ZAOfzlTQMs82c0p12HyVBvjx/CClMs45fWfO7E+uZsTS6RpRMmfALnCyVzNmig7xo3ykpP5lzNV5m/MJHya0n5pAreYD3iXG8u6lMh2toHINRG8KkQzOnyiH5oK3V6yUYca8VK+5aPeH5vPbtPT9eczQ7bw9dI5uxxBi0BgdYmyVn7QNubv/IchcDLFiNdZICTvI2a8/3BcMd9388mCc4oPw3vzLipaSNGxpHNtL0q7i/sn+quXM=" 
        secure: "TEfc491WUZJwCE006Sks7fMCvM2TOyWCCI1ZU/VwXtR9qrCg3qYNXRW77AA/fSskR+6vJ63mlaS5+Q3TCo55vAWaLNQ+GeJAIq54TqLA/vtC+SQf6+FWH2Q1uowas+aXtFbM1hkfYU+RCKFduB2kTaY1ZEqJujz1FwjPGMjJbS61MLtbHtykdV6U0ZmlKUsyTNQ4davBVTG3KURwaH5Cs/FVAWdRB6MV/fY8wFElVEgYCVtdC/y2FkKa/+RLRnpHgqM8iu5N7rEEyu0x80Dhj0o0/G00WTEdnYWwu+U+PKMQxKXC7d2Ym/51uKxk4H+r4YELr1D65CkoDPuXcrcv9h/DXrVy82NRACh1ndQWpczA0cUVYxWLvqBw8TOWirSVtjOJRyxewdBRefglxHi0E2Nf0d+/T0V2vmX9wIipsMhPXipU3kEAk9J2xdcX+nN1NlD1x6f3uV4VJpbl7ngmucq8H+YAOpAW1CXVGBxHmA75KbjS6YTgdK/rxsYVtKEDoI0H8HLUVnVsFN3nzMElYDWy530MTOWFnR6uwjaiP5JgjSOktfTOYQ+GMpARs4imfktmeIXBlX5rUM+71XmflyFko3JqtXoZOuOZw9vthU3sdwFaC80pkKyrFKX4sJuxCx30LDqLnL1cnlxV8szALvR+absH+ZkXijCaanllUSc="
        secure: "I2iRB9hG/937XQzaYtqm1yieKrIGtYpg56dDzYI5bHngW9wdnkMV5Xlt3fGvYkqnonrdsYIOuVeSDdO9mVhyharLk1Uy4Vo2UnJe7tvt25vXUTKDKyQh9y9b+hl9p6e8PVZzE/k5pGGIQHcPMAlCmp+m9aEmVyLOuAWPHOSjEUbd/RNUendeoP28jv7yqavPm7Sb0vAWxf4ao0JU8IYVcGTccF0CcybK2HZs+SR1YFkzVmz+UKMYovAAHStzO2SLMobIB99blGDKBdpYTcp3Ai7M82utsLw6DTZX/Jrfd2tZR7bjaRbx88G53ov9g/L0hOU3KPEXZeFf/cMB4PHOVEfK1SsT3j0jGDEaIhWiwM7kt8qHi2hLybzF1bZB/W8PcKjaHaCLvuPFwpfvEqyhZAKWpq8VINaJiuuj6i3zZA2eUJu2J0o/dKkk77V3p4e4yQaLnQXGAV2bORAHhX+q6twX8jTGabnaT0t3n2NgtejrqC3lF5ztwGuKl9fnrnWsuzpLc4xMfDUVvzXVas3dfPP6pz+UkNi1AG9dIt+uPcva8XBqEsUoqWbG/n2uvBpb46hhE9+RuDuifLKnSUPel1OeWR6HmiGvi131xZrv1I7rjAjjvMVDP24bmLgWrs+y/ou09hWANIynfzUedhS1/aUso58ItXWnPmu4GNJWJaY="
         secure: "qE6fSqYeU1G5aHsHMcFWqS1qgrMYbcF2dCapJmp3jDTqY2soSblAM6sg9cmSf62P6K8yMDkLhahovULcr+bVdviFb/jJMZV4FkFW40daObaLFDhajoXt5BoVj8SbqFfHZNbI0NYs+nNTmhSvlnxM86Uq314Y0XS9py99N4JK9Jn12FIhJpLEiAY/zmvaYNMXGNqycd5i67sxXKHnGxb2ZEeSlYG4XPwEnzx18CzZxSwYhVKi+rb8JATYuuqKLUXEEp9ZjL72FXL3SxKAxNBWlUIbkCTGS1+g5CBG2427pvmeg4yzbWDBXev31+IMiEqUums/OQmbIfHOyunJjRcrFWB+HAauvWQ9qbQdsZ3coE7yCZKlS1e19aSZmxj3ZxQU5pY2ivMHsr99vD2pgkPOaIRzUhSXOiBoeZBOypVGFm90anl9YiU1R5x2vmfEWVCLw3z2Bop+o3grWPE54wmWVEXzTZe8+qh6zpkNduPjE3+SwOtOISoW4D+cA9doL/yz4/NsYjPHUIvsVjob6yL+OCiSjjrhyjtJYZE+LmOfsIDHiXvzoG2ggqAJpbvV+9ia7SOlyJE2sNUqwDdmOJs1iTK3Y8qJjIL/Bxj5QlE3EDCpx+p9g3QpgZfbkntaiNWXZzcUY61ItbVjsvKvySPJgVjaoc/mwoJ4WEeOxQtPkX8="
         secure: "R2G3tuPCefzg+iJjlUPZC4hjrt8lOjQ5y40rFGBFKXYurynp9rKOXthr6atqGk9d1yooGUMsiaanjfQD4Xgf5wGcRDolL36gW6oJEm9c+qvWETE8i0W1XaQgipDSzTkkxBqGXXKE1a/QeZLJSug5UWEm2/W9x2vt3GE0VwlHvGvjN99GsuAmM308136fuQ9CDS9CT9bxogtVXImTNCpBpGyf5eZxh+EdLrqKP9UBAc+cYlNhhBiibXaCJJFyJsEBy5WTOFJt/lzsI3umh3UKDVTtv4SieJwBrVFUTeXyIwLfiL2mXmQfr377JLewdlxnbCDn0ONovixjbGiilB3bd8w+L31vr/U7wh4Qu6MekbvX6qA2LzJXto7B4MxGKZ0ApANQ7jxvDSHCC9VezW/i+/tlL3QkFUUZEEoDPtcz5zAP6D0MJdzd5Gx7HYh7ZP1qer9tDx9z/OOqTprTBko909y/EbvoAfSM/UbXAw4RM3vUhOcFTquPMAnCy1buF6480P1tDnMDjQtqjap8DfPqKkYW1vip51UGayH3KCE7OY92YOrzXefZav4NnUgP6kiyybcIfsh9sb+ZjMY2MIDl1WgyMgLpNLbsly1PPO1ovIQWU4AV03BVQLGKSXNFYwK4rQB9ewpEhnbS/+F+rQRtL9Kz40ZNl2h7jswnPIPQq54="

cache:
    directories: 
    - node_modules 

install: 
  - npm install 

script: 
# first build is needed, since webpack-typings-for-css-loader produces typings AFTER typescript-loader tries to load
# them. as far as I researched there is no easy way to fix it. Second build succeeds, because of typings from the first build  
  - npm run build:production || true 
  - npm run build:production 

before_deploy:
    - openssl aes-256-cbc -K $encrypted_0faef1a5218f_key -iv $encrypted_0faef1a5218f_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa

      
deploy:
  provider: script
  skip_cleanup: true
  script: scp -r -P $PRECICE_PORT  build $PRECICE_USR@$PRECICE_VM:
  on:
    branch: master
