language: node_js
node_js:
  - "7"

sudo: false 
dist: trusty 

cache:
    directories: 
    - node_modules 

install: 
  - npm install 

script: 
  - npm run build:production | true 
  - npm run build:production 
