language: node_js
node_js:
  - "7"

sudo: false 
dist: trusty 

env:
    global:
        - secure: "Bw0nIH1qKGV3mE58gdLaLcha/C5qdUTLxdf6OlP5aJx3eboeZQmwHbeTMSTpbGjX97I3Mj72s4MCCwPW13M/KNUflrLkCu753B5syUuE67y7EJ6/ugP7fxmDiKGIqqmyQtbQHB3PmLZG0eixeaSKowpZm++9GWRs+B/q9D/I5MTf6Q0juFREouxxtuwvwJxKLRkNtSzncrdWHJwa5cIRL3HulHlKzriXg4mE7omeDUOlbzeoJiVngZavsIp2x3+oxz8d4KqZF0qzc82pZGIBEsCndqCibm56PdZY78sQR0Gqx04SPyfgUfw91y3y4nxmVjfLdNuLaTndlqOluPxDvG8SK+tly9nodyFG+cqfvBzyYR7UuT5+f4pgRl+HKEuPtMZt/3c3rrjg8ieNIZKGBMIV703Sl6sQ1Bt2x+T3to739KfpnIKyykBgMJ4LmGRH1VJdWodSIYm6qMKZUPaZUWexc/OHQE34kyrh6iE69gdBbk7L0wVJHMTw3BjbJ5a0Lax9BLN2NK86lVhd8R33guEhNx5cNALBjitACsTGoMQjitMO0hmmjG2wZnw/+CDj8MAiGyQhI/hab/Tk+87Q5KsZtfLeUsLjMwowAvJyNG5qTFwIPwpxjb1aP/p1e7YxpMvF/qRbzLQ0Hdf6nXdYozOQ+lcPmiuEiD4pzwhc92Y="
        - secure: "PxMg9XigeCCVBK+AhBxU6ZRhiCLTQZHHA7z49DsxLLiOOEJ1p7Vec3YPQB2PHgG0qPvy473UlHTo18gVQLnrxujbUXer4WaoVqfLda4hfaSFh8iNiqzTcW++qJpaf7BgW6k82W4qIkp7d55Y8sZXotdo2sZun01ewjUj/ecPjBvzVOWbgzqvwh+fXyeJK+EDC4rw226mE+KCUVt4YADFrduhEymyj0P1EGrt4tVgHU223IJXT1LFj0iV4lovp+Oss5olisboRIOsQ07SWUVcdO1BJkCqpXX8SGb4e8PILFzi7GVpKG4dbCbBtVRq8PuYstnJcA4CRKYTTjnGPAlxVxklhfsWQFsELqrYtN348rKXuhhGS92pO1bXEscNzT/vv4RLA/hqXPymHuEMb9DICztpZWccykU0HhrE28GPFWsXcPfPhRbRpi13I+k5chSHu+4mFfRRl7lI/uDGtkgKkWr+z7ViZQtEgQkyeWABYydN+m9mdsuUPw4y9TKT3v/x+Lwi6NYpTtnDsf71MMeYNV0PEhNHZPTY+xeaDmaLizu36jEb7MnunMYy6sgALDY/nTB5QA1OWK59YNtXpUtEAhthxu/8GBPYbYGWS7JXOvRyjiU3Ywmy2gfIaF6afawFcS03r0ofo1GoCgZ4yLnfT3XaCZmbUBYazwV0d3GhcG8="
        - secure: "Th2qHKwMsW8bj5oLrjskaIAC8vnut4R/4bt6DD8TZVIoPzgBpqthHiJcDQD0vQw+jJ/MgB57DVEoG6k79PqVxoGx5mbgbOhuJJO6wK5UrDBX4aFjTUzQ1Ueqs/1UEqeFY/grnVlsakiqo2fvnlX1PS7yxNUBLNPsf/SBmXDUQB8xRYvO0SX7MnN/03GTM+aOGEbxcvn1FqtbRnpaywmVajvD/EUk/hn4dAC+zvAMSJ9ZlyIzWPzLdjJa/ad1XoYuhUSRUIkcVdzN3/Yh4G9veb39aFC6A/GLGOJtXlEfms4pazIZK0i8zuLOLnRUQappdkAE6l7LMvjqFgi18RS4ekN9LcMDBS8NINU8H+5PMjr4jcMuu1EAZSIbFvzHQHLe0Q/hmtd+/4ZJJgKoDO6yXneVUbdwwNNJkpDFfmEaHQVrS7rOgwlvPJ6RrTK3GbrolukKzSko9ovQNtLR3X14Pg0JBvVDCvP1rJyr9BeuaszGShrY5KPLCV1KABexYSdpzOtzGL8PHTV9dZD4P9LK4+ZfC4bVxh0m2tb1kIO8Abxorm874hbGN4J1PJ652tMbYxC/52IabHe4jZluzFX2tdUd9KOv7n7gDxWL0GGDGF9PZ8aLkU7xRT/wmHmftaAJuILtvpCxJ4mCUeIMW9wJGDZmmJ1a941CUIWFE3OHKzo="
        - secure: "bizZDZEnIcuH3bO1gOI1vo3vqzA2G/zC49zSiUd5xhJwfENNFeLC98pvWB17c7Xvy7+Tz/n3gy7ZWVPRniLLX33e48rh/Fsl1BSEboqUWZIlpUTjJhO7JcWK+xPsWBqSx36rC7Gj+Zuax3sX3a+3XxhYajqix6+PPHdtdxKjHX27agrQYzGjUSm08GCvK7RsEAfMPSloxaltZDFRqIrYz6ScVH4sCuV35IeV7sR25dOxGlqAx0yuqWDSfpEiS327ihP5EmYPHgSx5wBGYRrZezU1yKI4f7tTRIHNPBcHa6yYVTEzcR3i3Zz83/mQ7DT2y2eK6RA1A9t7dbqlCrt9vsK12Es+5JHeJSJQNdv9WeEd+UYeb2l+KAontrSY3kUOdcn55NCjrm+XLdwQeG/iloOj2yGjeZa1qDbqAv9NtnWO7oB+DTiVUr8a9bYC7MpXPQLonT5uyGhWmbqc99Zioz9iPCnLCsaYz+wdNBsBHcrirg++MNMOCsByq1u7cEdwBRgMcyQluCshWAScWKhAxO4nOe03LHDr/9Wi1IAieiBPvLyxCLea2MTDfcYylzqVFj8PiWjYMPkQ757CAyw2ZUvie98uw4cRquj3VEbSzVjKhLgAAv+50ZAste/3Cmn8OYAWSGRxSd2hGGAJP9lPpXzFBa9gKPTfe2jwzSjRDE8="
        - secure: "DLDMxDn7kk52zIeHBnG4Vwqeq7s+poTpwOSA0kvSWZogV1CAjQ4AUvHkO1JyGrBIP26hlHM8rqbBQtLeq48/ON2cdAEaF9YQ+Pouq4+Tvm8zcPGLtf4MKtJT5s7cpFq1igJafalt3xU9s6jntZvvWZI9OlHJUYSGx2q9dy9yqTyb22pJz/4uxv4feorDGkujbWS552nNiO6xhYC90rhvHz72nLB7yxqXa4ESTF4Nl1FBaD2pjAJEvMTL90yeIE7RzBz4oobBTatTNeGuqERnPb36FO/3r49WRM4Z4bih4NtCO1pWqiTj7p1Swx18Cl8OmJHMYNZQUC7H0tcpEL5OwgLaot7v5o6leR/B4fqI2FRpGxhilO4r8ajU3Rx+DRm2PsFX0KLie319UUIwQvom2/ifsaYovL9yyTvlJQruwpqHgSgru63ut7gNz193DeAm+o4NtUHdsWj6jJm0dhqOTN7B/HpKRfR0uj/zXRAChurVrE0Dtk5S3OcsjnGVJGjDDgPxx1livp0c/PqaT0Otv3B2DmPHuqR55fCZygJoNNJZ1qWKpq2YyDbYqDo6sOzJONxfB58EQA6LwPRAtpUfyLkJbMuIE3AXoaCtCR5OmygtN9+NLC/QVDAWOkCg1+FWkEaebZySGynUzVS7rNGNplvlQBcBkL0hHkQ+y7OPVVE="
        - secure: "WFWisM20T6wG4FxFJfBWoAASpdzl+F6pLlH6tX56tQaRF99lp1tuDJt9RNoMeMkLEmHmcFks5A/ws/GoufAI5l5LCicPMRz5seoi/TzGvMVjFA1jSCEFVOttoxSRuxGNGqoq4eLWoAcmOoM53j0azkU02KuuHhpoA7WfZrcYGtAUl/vKDW+HswAjgRAUEP3/W7GAJlL2kPf86XjoA+5WfjgxFEtKReB0i05PRGAlxAcye0OnJKU+C/xY8Dc1CMyLdnDWHrsuLxWin2Rp9CsRLTiid/a59i6Z8Tx3larTAK90k4SS6FfsrdhhXN0DQ+734HpDG2if+8wKKka/i1QM/HvlAt90IKowuyNazS0VXoimgvZkflBSrxOxSlZBBph5OrafF1dt+V7ZfI+8bZEbCjxleCthOxSfAogWjgTcebFvYzWbKuWHb+2uvcLF8AYskneot0NQCZvmIJO/xiruvB+yns92jwWCjpKRkdzWgobULz29UYyla9pHOitGobLmQlfeWhnh15cxiks5PLvFKN9HNQHqufdIIe5lSQKXCQvTedGP4e1GgzqG5++cF61fKmoXtzn58gSnsAs3rAvpSr1W88ag+1xtVdKHSYKDkMRbANwyo+5vYO5+wxr9uv7RzFWZ75WwmF1xv7zUJeIpuTacflDz0m8lHIpNuj71pHg="


cache:
    directories: 
    - node_modules 

install: 
  - npm install 

script: 
# first build is needed, since webpack-typings-for-css-loader produces typings AFTER typescript-loader tries to load
# them. as far as I researched there is no easy way to fix it. Second build succeeds, because of typings from the first build  
  - npm run build:production || true 
  - npm run build:production 

before_deploy:
    - openssl aes-256-cbc -K $encrypted_0faef1a5218f_key -iv $encrypted_0faef1a5218f_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa

      
deploy:
  provider: script
  skip_cleanup: true
  script: 
        scp -o  StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -qrP $PRECICE_PORT  build/. $PRECICE_USR@$PRECICE_VM:$TRAVIS_TEST_FOLDER && ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $PRECICE_USR@$PRECICE_VM "cp -r $TRAVIS_TEST_FOLDER/. $PRECICE_BUILD_FOLDER/"
  on:
    branch: master
