language: node_js
node_js:
  - "7"

sudo: false 
dist: trusty 

env:
    global:
        - secure: "qAuFIDNQITDSoQdmyEtbATXDZ0kbC8AzjLCdBmTlHEwXU6VFKoOtci5amWpQbTsFTS9h2/WG1Qt3PIejhbTHhwE2ItM31VzQg0NtbcQdN3Hcmw22mbjEHTRaUgJM18gdGTwThSRfHK4nq9RPeoQC5qqjvCqDv8bZ4RAADQMy7LyaXPKMUR52iB1n7g0DZx55LVbeuB0/JFcXDHh/k6BirrqMrMsIopfDjIsotHPveJ+8wvnkzTEN1n6ZgCCSRQzeYAQ1GhEtByXbfGoNYbrdKbRKqvDvE9Ul3UX3faRy2QR6rgPU753XyKoP5PXrg2B9HnYN9681g1nQTjTFW7AReV1Rzi3hXrg0QRVTxxUMoFncjULxiIo1OrKb/S13s4UFupo7bVJ5xi62n4pOLr+t9DYBqDRcTvtLav7LOf/7nXpLoL1TR129Zu3ZAOfzlTQMs82c0p12HyVBvjx/CClMs45fWfO7E+uZsTS6RpRMmfALnCyVzNmig7xo3ykpP5lzNV5m/MJHya0n5pAreYD3iXG8u6lMh2toHINRG8KkQzOnyiH5oK3V6yUYca8VK+5aPeH5vPbtPT9eczQ7bw9dI5uxxBi0BgdYmyVn7QNubv/IchcDLFiNdZICTvI2a8/3BcMd9388mCc4oPw3vzLipaSNGxpHNtL0q7i/sn+quXM=" 
        - secure: "TEfc491WUZJwCE006Sks7fMCvM2TOyWCCI1ZU/VwXtR9qrCg3qYNXRW77AA/fSskR+6vJ63mlaS5+Q3TCo55vAWaLNQ+GeJAIq54TqLA/vtC+SQf6+FWH2Q1uowas+aXtFbM1hkfYU+RCKFduB2kTaY1ZEqJujz1FwjPGMjJbS61MLtbHtykdV6U0ZmlKUsyTNQ4davBVTG3KURwaH5Cs/FVAWdRB6MV/fY8wFElVEgYCVtdC/y2FkKa/+RLRnpHgqM8iu5N7rEEyu0x80Dhj0o0/G00WTEdnYWwu+U+PKMQxKXC7d2Ym/51uKxk4H+r4YELr1D65CkoDPuXcrcv9h/DXrVy82NRACh1ndQWpczA0cUVYxWLvqBw8TOWirSVtjOJRyxewdBRefglxHi0E2Nf0d+/T0V2vmX9wIipsMhPXipU3kEAk9J2xdcX+nN1NlD1x6f3uV4VJpbl7ngmucq8H+YAOpAW1CXVGBxHmA75KbjS6YTgdK/rxsYVtKEDoI0H8HLUVnVsFN3nzMElYDWy530MTOWFnR6uwjaiP5JgjSOktfTOYQ+GMpARs4imfktmeIXBlX5rUM+71XmflyFko3JqtXoZOuOZw9vthU3sdwFaC80pkKyrFKX4sJuxCx30LDqLnL1cnlxV8szALvR+absH+ZkXijCaanllUSc="
        - secure: "I2iRB9hG/937XQzaYtqm1yieKrIGtYpg56dDzYI5bHngW9wdnkMV5Xlt3fGvYkqnonrdsYIOuVeSDdO9mVhyharLk1Uy4Vo2UnJe7tvt25vXUTKDKyQh9y9b+hl9p6e8PVZzE/k5pGGIQHcPMAlCmp+m9aEmVyLOuAWPHOSjEUbd/RNUendeoP28jv7yqavPm7Sb0vAWxf4ao0JU8IYVcGTccF0CcybK2HZs+SR1YFkzVmz+UKMYovAAHStzO2SLMobIB99blGDKBdpYTcp3Ai7M82utsLw6DTZX/Jrfd2tZR7bjaRbx88G53ov9g/L0hOU3KPEXZeFf/cMB4PHOVEfK1SsT3j0jGDEaIhWiwM7kt8qHi2hLybzF1bZB/W8PcKjaHaCLvuPFwpfvEqyhZAKWpq8VINaJiuuj6i3zZA2eUJu2J0o/dKkk77V3p4e4yQaLnQXGAV2bORAHhX+q6twX8jTGabnaT0t3n2NgtejrqC3lF5ztwGuKl9fnrnWsuzpLc4xMfDUVvzXVas3dfPP6pz+UkNi1AG9dIt+uPcva8XBqEsUoqWbG/n2uvBpb46hhE9+RuDuifLKnSUPel1OeWR6HmiGvi131xZrv1I7rjAjjvMVDP24bmLgWrs+y/ou09hWANIynfzUedhS1/aUso58ItXWnPmu4GNJWJaY="
        - secure: "KxCdFthHH9lHKIMtt2WLZk286Kh+HM7P1vSepe6w7s+8m/MNSFFaUGhr+gGctKehDAO3976109u5Arx94wyFRTqFgyGMMdlRPehCXvdWye/eJfaDStu96IvujEjgbG1J54flVgf2PNdxOmnSrZUtOrcx6CwumMetghzVBPPSMI22r25TQRcILkAlN+GyYord4sKSz8EGRG1XjGrH85odQyXmiVHAbw3dQurExcCmco5NMp7KJMgfaDfgETOu4Jt/NmJ2my+7alJEAfUDoAhdDLZk/4mjtt7McswAmBybGsTGxSRDwaFOgekv1EjWxNOtyT+Yo88YRbow4XKRTVZhFS1vsmuAdQNqSL0hj1oBUQrY7vv/9jcVQ73xsnSGNtjTKumDJMW0ivdP/OTO1BrVdtHQT5f20yEui3OOLkWfMtXUV4lQfTAqUXOs9f/AQ4JNGUQz360hHKeSr4L50PgEiRYIqAx99kzXJqCfD+zp6659Z3kZ/XBxd+mE8GlmFHZt1nxCjRZoHayKp5C2cka6d3GpLxZpNtK3M4fQj73kyDfyBc1tl819hNLcC+1vo5c7YQVmgwmPgRxOXmhP5+HvgCVbtADKww6CI72/vPTInzMh06aqESVmbWzQjiXeAfSj8aeQg/STT+3N0fgY4bMGwqeKbSnxwzxBtTHdUHNtHBk=" 
        - secure: "geW1vT7jseYdCYHe86AbfBIzwbAZAEkI92JioRuT6wrUod3hbHht6xKCTFbpthRerI9HUSnBD5YSXb0tkgNSFz/W8jQ1aa6lgExfexF7P4nBdmHYXFxssRJLRN97SSuxgtvzc2HYS8rjanOwKC5Idhjf/iuOJ6Gb7HT+Lw/QleDSbS7Fd4XR9EMVwgniTQQY/OuY4x5flr62YohkpldNwrUD5+DKXMZ2p2YI9Y+AhgqsMcctEUfs6wt9bkNyC83+BbTK2c/ApSsWrkCIpCLjkPXSZVewi8bRm13qn/CMDaJFbg5J4dZ9H7g3iTpMmYnzOa1UoMcj6CRBXkACqhgjqCHLZopZ95jki0SuY+Ouh59CC7yH5lDxGr5HXgWm56Hc7WuL6+vfv/36FIh0sQy+EQS+YaLOvu+2e00m2T/mKuZsud77SmFR7aAQx4LwJJumL1X1Ox4CC5j9mC83axDzb9MdS9zgyjIVKnLDn3gtUEh1PivIbWBaqJ7IsyRWRww0dlr2RpuM1/kq4Fjbqtx2mNSFeNOhITGulRjA3Kqb6puAtgf0UMSKHUoIVxmYAoCibhhEtu00OCDXHdkrmETpiCmJ1rD91YABuiIbgB0nbSwEUCiqEKYxLJdXwKMLpG3pJ3J0/f9A3fJIrfwXJdUiLT5rgf0dbZEh+zG23ko76OY="

cache:
    directories: 
    - node_modules 

install: 
  - npm install 

script: 
# first build is needed, since webpack-typings-for-css-loader produces typings AFTER typescript-loader tries to load
# them. as far as I researched there is no easy way to fix it. Second build succeeds, because of typings from the first build  
  - npm run build:production || true 
  - npm run build:production 

before_deploy:
    - openssl aes-256-cbc -K $encrypted_0faef1a5218f_key -iv $encrypted_0faef1a5218f_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa

      
deploy:
  provider: script
  skip_cleanup: true
  script: 
        scp -o  StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -qrP $PRECICE_PORT  build/. $PRECICE_USR@$PRECICE_VM:$TRAVIS_TEST_FOLDER && ssh $PRECICE_USR@$PRECICE_VM "cp -r $TRAVIS_TEST_FOLDER/. $PRECICE_BU#ILD_FOLDER/"
  on:
    branch: master
