language: node_js
node_js:
  - "7"

sudo: false 
dist: trusty 
notifications:
  email:
    recipients:
      - $MAINTAINER_MAIL@$MAIL_PROVIDER
    on_success: never
    on_failure: always


cache:
    directories: 
    - node_modules 

install: 
  - npm install 

script: 
# first build is needed, since webpack-typings-for-css-loader produces typings AFTER typescript-loader tries to load
# them. as far as I researched there is no easy way to fix it. Second build succeeds, because of typings from the first build  
  - npm run build:production || true 
  - npm run build:production 

before_deploy:
    - openssl aes-256-cbc -K $encrypted_d0e6b8903fb4_key -iv $encrypted_d0e6b8903fb4_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa

      
deploy:
  provider: script
  skip_cleanup: true
  script: 
        scp -o  StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -qrP $PRECICE_PORT  build/. $PRECICE_USR@$PRECICE_VM:$TRAVIS_TEST_FOLDER && ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $PRECICE_USR@$PRECICE_VM "cp -r $TRAVIS_TEST_FOLDER/. $PRECICE_BUILD_FOLDER/"
  on:
    branch: master
